name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create artifact
        run: echo world > app/hello2.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact2
          path: app/hello2.txt
      - name: Download link artifact
        uses: actions/download-artifact@v2
        id: download2
        with:
          name: my-artifact2
          path: app/hello2.txt
      - name: Echo download path
        run: echo ${{steps.download2.outputs.download-path}}