name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo https://ericksumargo.github.io/sherlock_page?r=${{ github.run_id }}